apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# transformer / add prefix | ALL resources
namePrefix: example-

resources:
# TODO: How to refer via relative path?
#  - ../deployment.yaml
#  - ../service.yaml
  - deployment.yaml
  - service.yaml