apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namePrefix: env1-
nameSuffix: -production

namespace: production

replicas:
  #- name: example-nginx
  - name: nginx
    count: 3

images:
  - name: nginx     # image's name
    newTag: 1.20.2  ## For the Staging overlay set this to 'latest'

labels:
  - pairs:
      variant: var1
    includeSelectors: false   # `false` ->  label NOT added | selectors
    includeTemplates: true  # `true` -> available ALSO | pod

patches:
  - patch: patch-env-vars.yaml

resources:
  - ../../base