apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namePrefix: env2-
nameSuffix: -staging

namespace: staging

replicas:
  #- name: example-nginx
  - name: nginx
    count: 2

images:
  - name: nginx       # image's name
    newTag: 1.20.2  ## For the Staging overlay set this to 'latest'

labels:
  - pairs:
      variant: var2
    includeSelectors: false # Setting this to false so that the label is not added to the selectors
    includeTemplates: true  # Setting this to true will make the label available also on the pod and not just the deployment

resources:
  - ../../base